# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeNode = channel.unary_unary(
                '/Discovery/ExchangeNode',
                request_serializer=grpc__pb2.Node.SerializeToString,
                response_deserializer=grpc__pb2.Node.FromString,
                _registered_method=True)
        self.Hello = channel.unary_unary(
                '/Discovery/Hello',
                request_serializer=grpc__pb2.Message.SerializeToString,
                response_deserializer=grpc__pb2.Message.FromString,
                _registered_method=True)
        self.ExchangeGrad = channel.unary_unary(
                '/Discovery/ExchangeGrad',
                request_serializer=grpc__pb2.Parameter.SerializeToString,
                response_deserializer=grpc__pb2.TensorReceive.FromString,
                _registered_method=True)
        self.Epoch_over = channel.unary_unary(
                '/Discovery/Epoch_over',
                request_serializer=grpc__pb2.Epoch.SerializeToString,
                response_deserializer=grpc__pb2.Epoch.FromString,
                _registered_method=True)
        self.ExchangeModel = channel.unary_unary(
                '/Discovery/ExchangeModel',
                request_serializer=grpc__pb2.Modelmessage.SerializeToString,
                response_deserializer=grpc__pb2.ModelReceive.FromString,
                _registered_method=True)


class DiscoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExchangeNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeGrad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Epoch_over(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeNode,
                    request_deserializer=grpc__pb2.Node.FromString,
                    response_serializer=grpc__pb2.Node.SerializeToString,
            ),
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=grpc__pb2.Message.FromString,
                    response_serializer=grpc__pb2.Message.SerializeToString,
            ),
            'ExchangeGrad': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeGrad,
                    request_deserializer=grpc__pb2.Parameter.FromString,
                    response_serializer=grpc__pb2.TensorReceive.SerializeToString,
            ),
            'Epoch_over': grpc.unary_unary_rpc_method_handler(
                    servicer.Epoch_over,
                    request_deserializer=grpc__pb2.Epoch.FromString,
                    response_serializer=grpc__pb2.Epoch.SerializeToString,
            ),
            'ExchangeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeModel,
                    request_deserializer=grpc__pb2.Modelmessage.FromString,
                    response_serializer=grpc__pb2.ModelReceive.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Discovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Discovery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Discovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExchangeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/ExchangeNode',
            grpc__pb2.Node.SerializeToString,
            grpc__pb2.Node.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/Hello',
            grpc__pb2.Message.SerializeToString,
            grpc__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeGrad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/ExchangeGrad',
            grpc__pb2.Parameter.SerializeToString,
            grpc__pb2.TensorReceive.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Epoch_over(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/Epoch_over',
            grpc__pb2.Epoch.SerializeToString,
            grpc__pb2.Epoch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/ExchangeModel',
            grpc__pb2.Modelmessage.SerializeToString,
            grpc__pb2.ModelReceive.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConsensusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadBlock = channel.unary_unary(
                '/Consensus/BroadBlock',
                request_serializer=grpc__pb2.Blockmessage.SerializeToString,
                response_deserializer=grpc__pb2.ConsensusRsp.FromString,
                _registered_method=True)
        self.BroadKey = channel.unary_unary(
                '/Consensus/BroadKey',
                request_serializer=grpc__pb2.Privatemessage.SerializeToString,
                response_deserializer=grpc__pb2.ConsensusRsp.FromString,
                _registered_method=True)
        self.BroadFinalBlock = channel.unary_unary(
                '/Consensus/BroadFinalBlock',
                request_serializer=grpc__pb2.FinalBlockMessage.SerializeToString,
                response_deserializer=grpc__pb2.ConsensusRsp.FromString,
                _registered_method=True)


class ConsensusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BroadBlock(self, request, context):
        """rpc PrePrepare (PrePrepareMsg) returns (ConsensusRsp);
        rpc Prepare (PrepareMsg) returns (ConsensusRsp);
        rpc Commit (CommitMsg) returns (ConsensusRsp);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadFinalBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadBlock,
                    request_deserializer=grpc__pb2.Blockmessage.FromString,
                    response_serializer=grpc__pb2.ConsensusRsp.SerializeToString,
            ),
            'BroadKey': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadKey,
                    request_deserializer=grpc__pb2.Privatemessage.FromString,
                    response_serializer=grpc__pb2.ConsensusRsp.SerializeToString,
            ),
            'BroadFinalBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadFinalBlock,
                    request_deserializer=grpc__pb2.FinalBlockMessage.FromString,
                    response_serializer=grpc__pb2.ConsensusRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Consensus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Consensus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Consensus(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BroadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Consensus/BroadBlock',
            grpc__pb2.Blockmessage.SerializeToString,
            grpc__pb2.ConsensusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Consensus/BroadKey',
            grpc__pb2.Privatemessage.SerializeToString,
            grpc__pb2.ConsensusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadFinalBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Consensus/BroadFinalBlock',
            grpc__pb2.FinalBlockMessage.SerializeToString,
            grpc__pb2.ConsensusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SynchronizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BlockFrom = channel.unary_unary(
                '/Synchronization/BlockFrom',
                request_serializer=grpc__pb2.Message.SerializeToString,
                response_deserializer=grpc__pb2.Block.FromString,
                _registered_method=True)
        self.BlockTo = channel.unary_unary(
                '/Synchronization/BlockTo',
                request_serializer=grpc__pb2.Block.SerializeToString,
                response_deserializer=grpc__pb2.Message.FromString,
                _registered_method=True)
        self.ExchangeBlock = channel.unary_unary(
                '/Synchronization/ExchangeBlock',
                request_serializer=grpc__pb2.Block.SerializeToString,
                response_deserializer=grpc__pb2.Block.FromString,
                _registered_method=True)
        self.TransactionTo = channel.unary_unary(
                '/Synchronization/TransactionTo',
                request_serializer=grpc__pb2.Transaction.SerializeToString,
                response_deserializer=grpc__pb2.Message.FromString,
                _registered_method=True)
        self.TransactionFrom = channel.unary_unary(
                '/Synchronization/TransactionFrom',
                request_serializer=grpc__pb2.Message.SerializeToString,
                response_deserializer=grpc__pb2.Transaction.FromString,
                _registered_method=True)


class SynchronizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BlockFrom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionFrom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SynchronizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BlockFrom': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockFrom,
                    request_deserializer=grpc__pb2.Message.FromString,
                    response_serializer=grpc__pb2.Block.SerializeToString,
            ),
            'BlockTo': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockTo,
                    request_deserializer=grpc__pb2.Block.FromString,
                    response_serializer=grpc__pb2.Message.SerializeToString,
            ),
            'ExchangeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeBlock,
                    request_deserializer=grpc__pb2.Block.FromString,
                    response_serializer=grpc__pb2.Block.SerializeToString,
            ),
            'TransactionTo': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionTo,
                    request_deserializer=grpc__pb2.Transaction.FromString,
                    response_serializer=grpc__pb2.Message.SerializeToString,
            ),
            'TransactionFrom': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionFrom,
                    request_deserializer=grpc__pb2.Message.FromString,
                    response_serializer=grpc__pb2.Transaction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Synchronization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Synchronization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Synchronization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BlockFrom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Synchronization/BlockFrom',
            grpc__pb2.Message.SerializeToString,
            grpc__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Synchronization/BlockTo',
            grpc__pb2.Block.SerializeToString,
            grpc__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Synchronization/ExchangeBlock',
            grpc__pb2.Block.SerializeToString,
            grpc__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Synchronization/TransactionTo',
            grpc__pb2.Transaction.SerializeToString,
            grpc__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionFrom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Synchronization/TransactionFrom',
            grpc__pb2.Message.SerializeToString,
            grpc__pb2.Transaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConnectionHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.info = channel.unary_unary(
                '/ConnectionHandler/info',
                request_serializer=grpc__pb2.ExpertUID.SerializeToString,
                response_deserializer=grpc__pb2.ExpertInfo.FromString,
                _registered_method=True)
        self.forward = channel.unary_unary(
                '/ConnectionHandler/forward',
                request_serializer=grpc__pb2.ExpertRequest.SerializeToString,
                response_deserializer=grpc__pb2.ExpertResponse.FromString,
                _registered_method=True)
        self.backward = channel.unary_unary(
                '/ConnectionHandler/backward',
                request_serializer=grpc__pb2.ExpertRequest.SerializeToString,
                response_deserializer=grpc__pb2.ExpertResponse.FromString,
                _registered_method=True)


class ConnectionHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def info(self, request, context):
        """Listens to incoming requests for expert computation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def backward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'info': grpc.unary_unary_rpc_method_handler(
                    servicer.info,
                    request_deserializer=grpc__pb2.ExpertUID.FromString,
                    response_serializer=grpc__pb2.ExpertInfo.SerializeToString,
            ),
            'forward': grpc.unary_unary_rpc_method_handler(
                    servicer.forward,
                    request_deserializer=grpc__pb2.ExpertRequest.FromString,
                    response_serializer=grpc__pb2.ExpertResponse.SerializeToString,
            ),
            'backward': grpc.unary_unary_rpc_method_handler(
                    servicer.backward,
                    request_deserializer=grpc__pb2.ExpertRequest.FromString,
                    response_serializer=grpc__pb2.ExpertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConnectionHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ConnectionHandler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectionHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ConnectionHandler/info',
            grpc__pb2.ExpertUID.SerializeToString,
            grpc__pb2.ExpertInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ConnectionHandler/forward',
            grpc__pb2.ExpertRequest.SerializeToString,
            grpc__pb2.ExpertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def backward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ConnectionHandler/backward',
            grpc__pb2.ExpertRequest.SerializeToString,
            grpc__pb2.ExpertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
